### ISSUE TITLE
[Listing Request]: <project name>

### ISSUE THREAD

**Issue by HOHToken** [DivvySD/dashboard#14]
### Contract Address

0x5FB567240374882BD565160CC61eB8927cF58E6d

### Project Name

Holdinghands

### Token Symbol

HOHSD

### Interested in Divvy Locker and Lava Flow?

- [ ] Yes

**Comment by CryptoJoshua** [comment]
This is the 1%?

https://bscscan.com/tx/0x2ad8193fada06349a6a20bf7a29f5481ae1cf45c69803cb8bc951dc767f10185

**Comment by HOHToken** [comment]
thx mate!

**Comment by HOHToken** [comment]
yep! supply total 475B

**Comment by HOHToken** [comment]
> This is the 1%?
> 
> https://bscscan.com/tx/0x2ad8193fada06349a6a20bf7a29f5481ae1cf45c69803cb8bc951dc767f10185



yes our total supply is 475B.

we send you 1% as requested.

**Comment by CryptoJoshua** [comment]
https://divvysd.com/dashboard/#/HOHSD

Need your info on fegex - https://docs.fegtoken.com/listing-on-fegex/how-to-submit-logo-and-info
