### ISSUE TITLE
[Locker/Faucet Request]: <FEG MARS>

### ISSUE THREAD

**Issue by FegMars** [DivvySD/dashboard#19]
### Contract Address

0x69b74406D9ce120cd77Fd2bCf8c2c80458DAAa8F

### Project Name

FEG MARS

### Token Symbol

FEM

### Amount of tokens for Divvy Locker

1210000

### Amount of tokens for Lava Flow

1210000

**Comment by CryptoJoshua** [comment]
Locker/Faucet are 1 BNB buy/burn of LAVA
You supply the tokens
