### ISSUE TITLE
[Locker/Faucet Request]: <GREENROCKET>

### ISSUE THREAD

**Issue by GREENROCKETSD** [DivvySD/dashboard#24]
### Contract Address

0x2AbAAa46964DcE8E00045F3711F3d04323864FB5

### Project Name

GREENROCKET

### Token Symbol

GREENROCKET

### Amount of tokens for Divvy Locker

30%

### Amount of tokens for Lava Flow

1 bnb

**Comment by CryptoJoshua** [comment]
Still need this?
