### ISSUE TITLE
[Locker/Faucet Request]: <Casino MetaFi>

### ISSUE THREAD

**Issue by CasinoFi** [DivvySD/dashboard#27]
### Contract Address

0xa35FE268de4924a87297BaD4DceB6B28B0351C49

### Project Name

Casino MetaFi

### Token Symbol

CMETAFI

### Amount of tokens for Divvy Locker

10000000

### Amount of tokens for Lava Flow

100000

**Comment by FEGjoshua** [comment]
Locker: 0x7853548b8c35e73C7E831e7919a0D739A53f7060
Faucet: 0xAAc2BE6dFc0Ce6A74489c8Cbc6b826e20Df0d15D
